name: Delete old published artefacts

env:
  BUILDS_SERVER: _couch/builds_testing
  STAGING_SERVER: _couch/builds
  MARKET_URL: ${{ secrets.MARKET_URL }}

jobs:
  cleanup:
    name: Deleting old published artefacts
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Cleanup
      run: |
        cd scripts/travis
        npm ci
        node ./cleanup.js
